# Generated by Django 5.1.4 on 2026-02-21 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('cafe_sessions', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='اسم العميل')),
                ('requested_hours', models.DecimalField(decimal_places=1, default=1, max_digits=4, verbose_name='عدد الساعات')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('status', models.CharField(choices=[('waiting', 'في الانتظار'), ('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='waiting', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التسجيل')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='activities.activitytype', verbose_name='نوع النشاط')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='cafe_sessions.tablesession', verbose_name='الجلسة')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table', verbose_name='الطاولة')),
            ],
            options={
                'verbose_name': 'عنصر طابور',
                'verbose_name_plural': 'عناصر الطابور',
                'ordering': ['activity_type', 'position'],
            },
        ),
    ]
