# Generated by Django 5.1.4 on 2026-03-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('queue_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='activity_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entry', to='activities.activitysession', verbose_name='جلسة النشاط'),
        ),
    ]
