# Generated by Django 5.1.4 on 2026-03-01 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('queue_system', '0002_queueentry_activity_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='activities.device', verbose_name='الجهاز المطلوب'),
        ),
    ]
