# Generated by Django 5.1.4 on 2026-02-21 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('method', models.CharField(choices=[('cash', 'كاش'), ('card', 'بطاقة')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الدفع')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='الخصم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='الكاشير')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='cafe_sessions.tablesession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'عملية دفع',
                'verbose_name_plural': 'عمليات الدفع',
                'ordering': ['-paid_at'],
            },
        ),
    ]
