# Generated by Django 5.1.4 on 2026-02-28 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='reports.cashiershift', verbose_name='الشيفت'),
        ),
        migrations.AddField(
            model_name='payment',
            name='shift_invoice_number',
            field=models.PositiveIntegerField(default=0, verbose_name='رقم الفاتورة في الشيفت'),
        ),
    ]
