# Generated by Django 5.1.4 on 2026-03-01 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_sessions', '0001_initial'),
        ('payments', '0002_payment_shift_payment_shift_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='cafe_sessions.tablesession', verbose_name='الجلسة'),
        ),
    ]
