# Generated by Django 5.1.4 on 2026-03-01 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('cafe_sessions', '0001_initial'),
        ('payments', '0003_alter_payment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='activity_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='activities.activitysession', verbose_name='جلسة النشاط'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cafe_sessions.tablesession', verbose_name='الجلسة'),
        ),
    ]
