# Generated by Django 5.1.4 on 2026-03-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_activity_session_alter_payment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المرتجع'),
        ),
    ]
