# Generated by Django 5.1.4 on 2026-02-21 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('active', 'نشطة'), ('closed', 'مغلقة')], default='open', max_length=20, verbose_name='الحالة')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الفتح')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('total_orders', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي الطلبات')),
                ('total_activities', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي الأنشطة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('guest_count', models.PositiveIntegerField(default=1, verbose_name='عدد الضيوف')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_sessions', to=settings.AUTH_USER_MODEL, verbose_name='فُتحت بواسطة')),
                ('primary_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_sessions', to='tables.table', verbose_name='الطاولة الرئيسية')),
                ('tables', models.ManyToManyField(related_name='sessions_set', to='tables.table', verbose_name='الطاولات')),
            ],
            options={
                'verbose_name': 'جلسة',
                'verbose_name_plural': 'الجلسات',
                'ordering': ['-opened_at'],
            },
        ),
    ]
