# Generated by Django 5.1.4 on 2026-03-01 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_sessions', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesession',
            name='primary_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_sessions', to='tables.table', verbose_name='الطاولة الرئيسية'),
        ),
    ]
