# Generated by Django 5.1.4 on 2026-02-21 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم النشاط')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='سعر الساعة')),
                ('icon', models.CharField(default='🎮', max_length=50, verbose_name='أيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نوع نشاط',
                'verbose_name_plural': 'أنواع الأنشطة',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الجهاز')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('busy', 'مشغول'), ('maintenance', 'صيانة')], default='available', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='activities.activitytype', verbose_name='نوع النشاط')),
            ],
            options={
                'verbose_name': 'جهاز',
                'verbose_name_plural': 'الأجهزة',
            },
        ),
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='الإجمالي')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to='cafe_sessions.tablesession', verbose_name='جلسة الطاولة')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to='activities.device', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'جلسة نشاط',
                'verbose_name_plural': 'جلسات الأنشطة',
                'ordering': ['-started_at'],
            },
        ),
    ]
