# Generated by Django 5.1.4 on 2026-03-01 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payday',
            field=models.PositiveIntegerField(default=1, help_text='يوم الشهر (1-28)', verbose_name='يوم القبض'),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المرتب الشهري'),
        ),
        migrations.CreateModel(
            name='StaffAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_advances', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_advances', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_advances', to='reports.cashiershift', verbose_name='الشيفت')),
            ],
            options={
                'verbose_name': 'سلفة',
                'verbose_name_plural': 'السلف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='وصف الطلب')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_orders', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_orders', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_orders', to='reports.cashiershift', verbose_name='الشيفت')),
            ],
            options={
                'verbose_name': 'طلب موظف',
                'verbose_name_plural': 'طلبات الموظفين',
                'ordering': ['-created_at'],
            },
        ),
    ]
