# Generated by Django 5.1.4 on 2026-02-21 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='رقم الطاولة')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='اسم الطاولة')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('empty', 'فارغة'), ('occupied', 'مشغولة'), ('pending', 'طلبات معلقة'), ('activity', 'نشاط شغال'), ('reserved', 'محجوزة')], default='empty', max_length=20, verbose_name='الحالة')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='السعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.floor', verbose_name='الطابق')),
            ],
            options={
                'verbose_name': 'طاولة',
                'verbose_name_plural': 'الطاولات',
                'ordering': ['floor', 'number'],
                'unique_together': {('floor', 'number')},
            },
        ),
    ]
