# Generated by Django 5.1.4 on 2026-03-01 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_shift_order_shift_order_number'),
        ('products', '0002_product_has_sizes_alter_product_price_productsize'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المادة')),
                ('unit', models.CharField(choices=[('ml', 'ملليلتر (ml)'), ('g', 'جرام (g)'), ('piece', 'قطعة'), ('bottle', 'زجاجة'), ('kg', 'كيلو (kg)'), ('liter', 'لتر'), ('pack', 'عبوة'), ('plate', 'طبق'), ('loaf', 'رغيف')], default='piece', max_length=20, verbose_name='وحدة القياس')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الكمية الحالية')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, help_text='سيتم التنبيه عند وصول الكمية لهذا الحد', max_digits=12, verbose_name='الحد الأدنى')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='اختياري - لحساب التكاليف', max_digits=10, verbose_name='تكلفة الوحدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مادة خام',
                'verbose_name_plural': 'المواد الخام',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'وارد'), ('out', 'صادر'), ('adjustment', 'تعديل جرد'), ('waste', 'هالك')], max_length=20, verbose_name='نوع الحركة')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem', verbose_name='المادة الخام')),
                ('reference_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='orders.order', verbose_name='الطلب المرتبط')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='reports.cashiershift', verbose_name='الشيفت')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, help_text='الكمية من المادة الخام لكل وحدة من المنتج', max_digits=10, verbose_name='الكمية المستخدمة')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usages', to='inventory.inventoryitem', verbose_name='المادة الخام')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'مكون منتج',
                'verbose_name_plural': 'مكونات المنتجات',
                'unique_together': {('product', 'inventory_item')},
            },
        ),
    ]
