# Generated by Django 5.1.4 on 2026-03-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productingredient',
            name='usage_unit',
            field=models.CharField(blank=True, choices=[('ml', 'ملليلتر (ml)'), ('g', 'جرام (g)'), ('piece', 'قطعة'), ('bottle', 'زجاجة'), ('kg', 'كيلو (kg)'), ('liter', 'لتر'), ('pack', 'عبوة'), ('plate', 'طبق'), ('loaf', 'رغيف')], help_text='الوحدة اللي بتخصم بيها (لو فاضية هتستخدم نفس وحدة المادة الخام)', max_length=20, verbose_name='وحدة الاستخدام'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='quantity_used',
            field=models.DecimalField(decimal_places=3, help_text='الكمية لكل وحدة من المنتج (بوحدة الاستخدام)', max_digits=10, verbose_name='الكمية المستخدمة'),
        ),
    ]
