# Generated by Django 5.1.4 on 2026-02-28 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت البداية')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الإيرادات')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='عدد الطلبات')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='عدد الجلسات')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي الخصومات')),
                ('total_activities_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إيرادات الأنشطة')),
                ('total_activities_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأنشطة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_shifts', to=settings.AUTH_USER_MODEL, verbose_name='أنهى بواسطة')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_shifts', to=settings.AUTH_USER_MODEL, verbose_name='بدأ بواسطة')),
            ],
            options={
                'verbose_name': 'شيفت',
                'verbose_name_plural': 'الشيفتات',
                'ordering': ['-started_at'],
            },
        ),
    ]
