# Generated by Django 5.1.4 on 2026-03-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiershift',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'صباحي'), ('afternoon', 'بيات'), ('night', 'ليلي')], default='morning', max_length=20, verbose_name='نوع الشيفت'),
        ),
    ]
