# Generated by Django 5.1.4 on 2026-02-28 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_size_orderitem_size_name'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_list', to='reports.cashiershift', verbose_name='الشيفت'),
        ),
        migrations.AddField(
            model_name='order',
            name='shift_order_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الطلب في الشيفت'),
        ),
    ]
