# Generated by Django 5.1.4 on 2026-03-01 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_sessions', '0001_initial'),
        ('orders', '0003_order_shift_order_shift_order_number'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_takeaway',
            field=models.BooleanField(default=False, verbose_name='تيك أواي'),
        ),
        migrations.AlterField(
            model_name='order',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cafe_sessions.tablesession', verbose_name='الجلسة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tables.table', verbose_name='الطاولة'),
        ),
    ]
