# Generated by Django 5.1.4 on 2026-03-01 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_takeaway_alter_order_session_and_more'),
        ('products', '0002_product_has_sizes_alter_product_price_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='label',
            field=models.CharField(blank=True, max_length=200, verbose_name='وصف مخصص'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='المنتج'),
        ),
    ]
