# Generated by Django 5.1.4 on 2026-02-21 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(default=False, verbose_name='له أحجام مختلفة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر الافتراضي'),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('small', 'صغير'), ('medium', 'وسط'), ('large', 'كبير')], max_length=20, verbose_name='الحجم')),
                ('name', models.CharField(blank=True, help_text='اتركه فارغ لاستخدام الاسم الافتراضي', max_length=50, verbose_name='اسم مخصص')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'حجم منتج',
                'verbose_name_plural': 'أحجام المنتجات',
                'ordering': ['order'],
                'unique_together': {('product', 'size')},
            },
        ),
    ]
